url: https://weasels.co
title: Weasels Sp. z o.o.
email: michal.lasecki@weasels.co
markdown: kramdown
permalink: pretty
collections:
  gallery:
    output: true
    permalink: /gallery/
encoding: utf-8
page-title: 'Weasels Sp. z o. o.'
text:
  navbar:
    header: 'mike'
    links:
      home: 'Start'
      about: 'O Firmie'
      services: 'Usługi'
      contact: 'Kontakt'
      tabor: 'Tabor'
  content:
    block-1-title: 'Wszechstronność'
    block-1: 'Dalekie trasy to nasza specjalność. Nasi kierowcy to doświadczeni pracownicy z wieloletnią praktyką. Stawiamy, na jakość i bezpieczeństwo prowadzonych działań. Transport krajowy to dla nas codzienność.'
    block-2-title: 'Transport ponadgabarytowy'
    block-2: 'Maszyny budowlane, rolnicze czy ładunki nietypowe? Chętnie podejmujemy się transportów naczepą niskopodłogową do przewozu ładunków ponadgabarytowych.'
    block-3-title: 'Spedycja'
    block-3: 'Codziennie jesteśmy do Państwa dyspozycji, gwarantując, profesjonalne wykonanie powierzonych nam działań. Jakość i niezawodność jest domeną naszej działalności.'
    block-4-title: 'Monitorowanie'
    block-4: 'Ciągniki wyposażone są w system GPS pozwalający na nieprzerwaną łączność z pojazdem co jest dla Państwa dodatkową gwarancją bezpieczeństwa powierzonych ładunków.'
    block-5-title: 'Dyspozycyjność'
    block-5: 'Jesteśmy firmą ceniącą Klienta, dbamy o jakość, terminowość i rzetelność wykonywanych usług transportowych. Do każdego zlecenia podchodzimy profesjonalnie, zaufało nam wielu przedsiębiorców.'
    made-by: 'łasica'
    copyright: '2016 © Weasels. Wszelkie prawa zastrzeżone.'
  gallery:
    title: Transport międzynarodowy, maszyn rolniczych i budowlanych
  about:
    poczatki: |
      Spółka powstała w 2016 roku, chociaż początki Naszej przygody z transportem sięgają 1989 roku. Początkowo dysponowała jednym pojazdem, a jego kierowcą był właściciel.

      Z roku na rok flota sukcesywnie się powiększała starsze zestawy zostały zastąpione nowymi i w chwili obecnej dysponujemy zestawami typu ciągnik z naczepą o kubaturze 90-100 m³ oraz zestawem z naczepą niskopodłogową do przewozu maszyn budowlanych oraz rolniczych.

      Naszym celem jest dalszy rozwój oraz dążenie do jak najwyższej jakości świadczonych przez nas usług.
    uslugi: 'Naszą główną domeną są przewozy ładunków na terenie Unii Europejskiej. Chętnie podejmujemy się transportów do innych krajów, zgodnie z życzeniem klienta. Towar ubezpieczony jest polisą OC przewoźnika w ruchu międzynarodowym i krajowym. Posiadamy naczepy przeznaczone do transportu maszyn rolniczych oraz budowlanych.'
  contact:
    michal-tel: '+48 726 922 069'
    michal: 'Michał Łasecki'
    michal-mail: 'michal.lasecki@weasels.co'
    maciej-tel: '+48 727 907 796'
    maciej: 'Maciej Łasecki'
    maciej-mail: 'maciej.lasecki@weasels.co'
    address: |
      ul. Leśna 24a
      62-100 Wągrowiec
      woj. wielkopolskie
      Polska
    base-location: 'ul. Leśna 24a, 62-100 Wągrowiec, woj. wielkopolskie, Polska'
  footer:
    name: 'weasels sp. z o. o.'
    about-1: |
      Nasza firma transportowa pragnie dostarczyć pełen wachlarz usług w zakresie drogowego transportu krajowego i międzynarodowego. Usługi transportowe i spedycja to nasza specjalność, a także pasja!
      W naszych działaniach jesteśmy niezawodni, ciesząc się uznaniem oraz zaufaniem Klientów w kraju, jak również za granicą. Stawiamy na jakość!
    about-2: 'Realizujemy się na wielu płaszczyznach, co daje nam wymierny efekt w postaci konkurencyjnych cen. W zakresie przewozu ładunków taborem ciężarowym na terenie całej Polski dostarczamy pełną ofertę zarówno w obsłudze logistycznej, jak i spedycyjnej.'
    about-4: 'Realizujemy zamówienia zarówno od dużych Przedsiębiorstw, jak i małych Firm. Dla nas liczy się indywidualne podejście do świadczonych usług. Codziennie jesteśmy dla Państwa!'
    about-3: 'Jesteśmy firmą ceniącą Klienta, dbamy o jakość, terminowość i rzetelność wykonywanych usług transportowych. Ufamy naszym kierowcom. Ich doświadczenie i kwalifikacje sprawiają, że kiedy oni codziennie wyruszają w trasę, my mamy pewność realizacji Państwa zamówienia. Nasi spedytorzy są z nimi w stałym kontakcie, dzięki czemu na bieżąco mogą Państwo śledzić trasę swojej przesyłki. Dbamy o jej bezpieczeństwo, dlatego towar jest ubezpieczony – OC Przewoźnika, tzw. OCP. Jesteśmy firmą transportową posiadającą bardzo bogaty oraz rozbudowany tabor, by świadczone przez nas usługi transportowe, spedycyjne gwarantowały Państwu pełną kompleksowość. Nasza firma również przygotowana jest do przewożenia ładunków niebezpiecznych (ADR).'
    details: 'Dane firmy'
    nip: 'PL 766 199 52 94'
    nip-t: 'NIP:'
    krs: '0000635743'
    krs-t: 'KRS:'
    regon: '365359540'
    regon-t: 'Regon:'
    location: 'ul. Brzozowa 13, 62-100 Wągrowiec, woj. wielkopolskie, Polska'
    base-location: 'ul. Leśna 24a, 62-100 Wągrowiec, woj. wielkopolskie, Polska'
    location-t: 'Siedziba:'
    spec: 'Transport Drogowy Towarów ( PKD : 49.41.Z )'
    spec-t: 'Działalność:'
    finance: '80.000,00 zł'
    finance-t: 'Kapitał zakładowy'
    email: 'transport@weasels.co'
    court: 'Sąd Rejonowy w Wągrowcu. ul. Kościuszki 18. 62-100 Wągrowiec'
plugins_dir:
  - jekyll-seo-tag
  - jekyll-haml
  - jekyll-sitemap
